name: remnawave

services:
  remnawave-redis:
    image: valkey/valkey:8.0.2-alpine
    container_name: remnawave-redis
    restart: always
    volumes:
      - ./redis:/data

  remnawave:
    image: remnawave/backend:latest
    container_name: remnawave
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - ./.env
    depends_on:
      - remnawave-redis

  remnawave-subscription:
    image: remnawave/subscription-page:latest
    container_name: remnawave-subscription
    restart: always
    ports:
      - 127.0.0.1:3010:3010
    env_file:
      - ./.env
    volumes:
      - ./app-config.json:/opt/app/frontend/assets/app-config.json
    depends_on:
      - remnawave

  swag:
    image: lscr.io/linuxserver/swag
    container_name: swag
    restart: always
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Moscow
      - URL= # Top url you have control over
      - SUBDOMAINS=panel,sub
      - VALIDATION=http
      - ONLY_SUBDOMAINS=true
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - ./swag:/config
    depends_on:
      - remnawave
      - remnawave-subscription
