name: remnawave

services:
  remnawave-db:
    image: postgres:17
    container_name: remnawave-db
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./db:/var/lib/postgresql/data

  remnawave-redis:
    image: valkey/valkey:8.0.2-alpine
    container_name: remnawave-redis
    restart: always
    volumes:
      - ./redis:/data

  remnawave:
    image: remnawave/backend:latest
    container_name: remnawave
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 127.0.0.1:3000:3000
    env_file:
      - ./.env
    depends_on:
      - remnawave-db
      - remnawave-redis

  remnawave-subscription:
    image: remnawave/subscription-page:latest
    container_name: remnawave-subscription
    restart: always
    ports:
      - 127.0.0.1:3010:3010
    env_file:
      - ./.env
    volumes:
      - ./app-config.json:/opt/app/frontend/assets/app-config.json
    depends_on:
      - remnawave
