client_max_body_size 0;
client_body_timeout 5m;
client_header_timeout 5m;

keepalive_timeout 5m;
grpc_read_timeout 5m;
grpc_send_timeout 5m;

grpc_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

location /api/v1/finland/ {
    grpc_pass grpc://127.0.0.1:10000;
}

location /api/v1/iceland/ {
    grpc_pass grpc://127.0.0.1:10001;
}

location /api/v1/proxy/ {
    grpc_pass grpc://127.0.0.1:10002;
}

location /api/v1/warp/ {
    grpc_pass grpc://127.0.0.1:10003;
}

location /api/v1/direct/ {
    grpc_pass grpc://127.0.0.1:10004;
}
