name: remnanode

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    environment:
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: remnanode --cleanup

  curl-cron:
    image: jsonfry/curl-cron:latest
    container_name: curl-cron
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./download:/download

  remnanode:
    image: remnawave/node:latest
    container_name: remnanode
    restart: always
    network_mode: host
    env_file:
      - ./.env
    volumes:
      - ./download/ip-v2fly.dat:/usr/local/share/xray/ip-v2fly.dat
      - ./download/site-v2fly.dat:/usr/local/share/xray/site-v2fly.dat
      - ./download/ip-antizapret.dat:/usr/local/share/xray/ip-antizapret.dat
      - ./download/site-antizapret.dat:/usr/local/share/xray/site-antizapret.dat
