name: darknet

services:
  i2p:
    image: geti2p/i2p:latest
    container_name: i2p
    restart: always
    environment:
      - JVM_XMX=256m
      - EXT_PORT=54321
    ports:
      - 127.0.0.1:4444:4444
      - 127.0.0.1:4445:4445
      - 127.0.0.1:7657:7657
      - 54321:12345
      - 54321:12345/udp
    volumes:
      - ./i2pconfig:/i2p/.i2p
      - ./i2ptorrents:/i2psnark

  torproxy:
    image: dperson/torproxy:latest
    container_name: torproxy
    restart: always
    ports:
      - 127.0.0.1:8118:8118
      - 127.0.0.1:9050:9050
      - 127.0.0.1:9050:9050/udp
